# Generated by Django 3.0.8 on 2020-10-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('Enfrentamiento', 'Enfrentamiento'), ('Influencia', 'Influencia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mythology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('Acción', 'Acción'), ('Equipo', 'Equipo'), ('Evento', 'Evento'), ('Invocación', 'Invocación'), ('Panteón', 'Panteón'), ('Personaje', 'Personaje'), ('Recurso', 'Recurso')], max_length=20)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('init_pow', models.IntegerField(blank=True, null=True)),
                ('max_pow', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('passive_effect', models.CharField(blank=True, max_length=200, null=True)),
                ('quote', models.CharField(max_length=200)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('abilities', models.ManyToManyField(blank=True, null=True, to='cards.Ability')),
                ('eras', models.ManyToManyField(to='cards.Era')),
                ('mythology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Mythology')),
                ('tags', models.ManyToManyField(to='cards.Tag')),
            ],
        ),
    ]
