# Generated by Django 3.0.8 on 2020-10-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='abilities',
            field=models.ManyToManyField(to='cards.Ability'),
        ),
        migrations.AlterField(
            model_name='card',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
