# Generated by Django 3.0.8 on 2021-02-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='quote',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
